### ISSUE TITLE
Recommended build process fails on Mac OS X, probably others

### ISSUE THREAD

**Issue by ghost** [koanlogic/klone#1]
Klone’s [recommended build process](http://www.koanlogic.com/klone/tut.html) fails to complete on Mac OS X, and probably also on other platforms without intervention, because of a dependency on `wget`. Using `curl` as a fallback would resolve the issue for at least Mac OS X.

wget isn’t part of a standard Mac OS X installation, even after installing the developer tools. Mac OS X doesn’t have a standard package repository either, so would-be Klone users are left to find and install wget from a third party source.

If I remember correctly, wget isn’t part of a base FreeBSD system either, though installing it on FreeBSD is more straightforward.

curl is part of a standard installation on Mac OS X, and it seems to be common on Linux systems too. FreeBSD also ships with a similar tool, `fetch`. Supporting these as fallbacks when wget is unavailable would improve portability, at least for the build process.

**Comment by babongo** [comment]
You're right, and in fact all the ready-made klapp's at http://wiki.koanlogic.com/doku.php?id=klone have a slightly different Makefile than the one in the tutorial:

<pre>
# set the following as needed (wget should be ok on most platforms)
#export FETCH_CMD = curl -O
#export FETCH_CMD = ftp
#export FETCH_CMD = fetch
export FETCH_CMD = wget

[KLONE_... vars settings]

include klapp.mk

klapp.mk: ; $(FETCH_CMD) http://koanlogic.com/klone/klapp.mk
</pre>


I think it's time for us to upgrade the site :)
Thanks, t.

**Comment by stewy** [comment]
The tutorial has had a comment on FETCH_CMD for a while, but we forgot to close the issue.
